/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABreadcrumb: typeof import('@arco-design/web-vue')['Breadcrumb']
    ABreadcrumbItem: typeof import('@arco-design/web-vue')['BreadcrumbItem']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AInput: typeof import('@arco-design/web-vue')['Input']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ArcoUpload: typeof import('./src/components/arcoUpload/index.vue')['default']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATrigger: typeof import('@arco-design/web-vue')['Trigger']
    AUpload: typeof import('@arco-design/web-vue')['Upload']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
